### ISSUE TITLE
Hiding off-by-one adjustments in NekDriver

### ISSUE THREAD

**Issue by paulromano** [enrico-dev/enrico#101]
@RonRahaman @pshriwise @lebuller and I discussed on a call this morning that the `+ 1` that is needed when going from 0-based arrays in ENRICO to 1-based arrays in Nek5000 should be pushed one level down, i.e., calls to `temperature_at()` and friends should not include the `+ 1`. Instead those should happen at the point Nek functions are called.

**Comment by lebuller** [comment]
In addition to the Nek5000 calls to temperature_at() and other such functions, it appears there is an off-by-one adjustment in `coupled_driver.cpp` in the loop where `heat.set_heat_source_at is called`, which loops from 1 to `n_local_elem`.

**Comment by RonRahaman** [comment]
@lebuller Thanks for catching that issue in `CoupledDriver`!  It tripped me up when I was working on the NekRS driver.
