### ISSUE TITLE
CMake fails for Nek5000

### ISSUE THREAD

**Issue by fuad1133** [enrico-dev/enrico#124]
I(Ubuntu20.04) ran this command on the build directory:
`CC=mpicc CXX=mpicxx FC=mpifort cmake -DNEK_DIST=nek5000 -DUSR_LOC=../tests/singlerod/short/nek5000 ..`

Here is the error message: 

>-- Compiling with Nek5000
-- Could NOT find SCALE (missing: SCALE_DIR)
-- Nek5000 configured with 'rodcht.usr' found in /home/fuad/thermal/enrico/tests/singlerod/short/nek5000
CMake Error at /usr/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:146 (message):
  Could NOT find BLAS (missing: BLAS_LIBRARIES)
Call Stack (most recent call first):
  /usr/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:393 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-3.16/Modules/FindBLAS.cmake:810 (find_package_handle_standard_args)
  /usr/share/cmake-3.16/Modules/FindLAPACK.cmake:197 (find_package)
  vendor/nek5000/CMakeLists.txt:453 (find_package)-- Configuring incomplete, errors occurred!
See also "/home/fuad/thermal/enrico/build/CMakeFiles/CMakeOutput.log".
See also "/home/fuad/thermal/enrico/build/CMakeFiles/CMakeError.log".

The error files are:
[CMakeError.log](https://github.com/enrico-dev/enrico/files/5977666/CMakeError.log)
[CMakeOutput.log](https://github.com/enrico-dev/enrico/files/5977667/CMakeOutput.log)

NB: I was able to compile and install NekRS and successfully run examples.

**Comment by AI-Pranto** [comment]
@fuad1133 You have to install `BLAS` and `LAPACK`.
```bash
sudo apt-get install libblas-dev liblapack-dev
```
