### ISSUE TITLE
Create HeatFluidsDriver base class

### ISSUE THREAD

**Issue by paulromano** [enrico-dev/enrico#14]
Moving issue 28 from gitlab originally submitted by @aprilnovak:

To make it clear what the requirements are of a single-physics heat-fluids driver, we should have a common base class that defines the interfaces to accessing temperature and density. This concept is similar to the base class we have for neutronics drivers.

**Comment by paulromano** [comment]
Comment by @aprilnovak:

To retrieve temperatures from Nek, we use a Gatherv to grab local element temperatures. But, instead of grabbing density, we instead set it in the `OpenmcNekDriver` by directly calling a correlation as a function of pressure and temperature.

In the future, we might want to apply relaxation on density, and would therefore need `densities_` and `densities_prev_` in a manner similar to how we're storing `temperatures_` and `temperature_prev_` in `CoupedDriver`. I think there are (at least) two options for storing current and previous density:

1. Add a new interface method, like `nek_get_local_elem_densities` to grab density in a manner similar to how we retrieve temperatures. The methods in `vendor/surrogates/iapws` would be called from `nek_get_local_elem_densities`. The length of `densities_` would be `n_global_elem_` minus the number of elements that are solid (i.e. `nelgv`, I think)

2. Leave the `nek_interface.f` as-is and interpret `densities_` as having a mapping similar to `heat_source_`, i.e. it is organized according to the OpenMC model. In other words, the length of `densities_` would be `n_materials_`. 

@rahaman and @romano, do you have any thoughts on how to go about this? I slightly prefer option 1 because there would be a more clear similarity between how temperature and density are grabbed from Nek. Option 1 would also permit future extensions to models in Nek that solve for density or if pressure isn't assumed constant (right now it's a constant from `enrico.xml`).

A third option would be to not store densities at all and leave things as-is.

**Comment by paulromano** [comment]
Comment by @RonRahaman:

Currently, we do not collect a `densities_` array that inclucdes every OpenMC cell nor Nek element because we only update density for fluid cells.  If you look in `OpenmcNekDriver::update_density` ([link](https://xgitlab.cels.anl.gov/stream/stream/blob/master/src/openmc_nek_driver.cpp#L330)), you'll see that we have something like:

```
for each cell:
    if cell contains fluid:
        for each element in cell:
            accumulate average density
        update cell density
```

Considering that the solid-only cells and elements aren't used in the density update, I have a couple of questions about your relaxation scheme:
1. Are we going to apply relaxation to only the fluid region?  (I'm guessing yes)
2. Do we want to keep a `densities_` array for all cells/elements?  (I'm guessing no)
   1. If yes, are we going to have a mask for `densities_` that only selects the fluid regions?
   2. If no, will the length of `densities_` be equal to the number of fluid-only cells?

**Comment by paulromano** [comment]
Comment by @aprilnovak:

Yes, with either of the options 1 and 2 that I listed above, I envision that `densities_` only refers to the fluid regions. This would either be reflected in the length of `densities_` being smaller than the length of `temperatures_`, or by applying a mask, as you've mentioned.

What I'm referring to is basically:

Do we want the length of `densities_` to be the number of Nek fluid cells, or the number of OpenMC fluid materials? If we want it to be similar to how we handle temperature (length equal to number of Nek global elements), then I think we could add an interface to Nek to grab density using the IAPWS correlation, rather than applying the correlation within `OpenmcNekDriver` (which doesn't seem like OOP-like to me if in the future we want to use a pressure solution from Nek instead of `pressure_` from `enrico.xml`).

**Comment by paulromano** [comment]
Comment by @RonRahaman:

> If we want it to be similar to how we handle temperature (length equal to number of Nek global elements)

This would be easiest, since we could probably use the same MPI communication pattern as all the other global element arrays.  We already have the `elem_is_in_fluid` mask, so that might come in handy?

>  I think we could add an interface to Nek to grab density using the IAPWS correlation, rather than applying the correlation within `OpenmcNekDriver`

@merzari had the same idea.  It would make the interfaces much easier.  I can take a stab at this part of the issue.

**Comment by paulromano** [comment]
Comment by @aprilnovak:

Sounds good! I'll add a method to get density from Nek once that interface is in there.

**Comment by paulromano** [comment]
Comment by @RonRahaman:

What density value do you want for an element that's not in fluid?

**Comment by paulromano** [comment]
Comment by @aprilnovak:

Maybe we could read density of materials from the OpenMC input files, and just never change the solid ones? Then the density values would all be meaningful. Or we could just hacky set it to zero or something...

Or maybe we make the length of `densities_` equal only to the number of fluid elements in Nek and not have to worry about it?

I don't feel strongly either way about what the length of `densities_` should be - all elements or just fluid ones.

**Comment by paulromano** [comment]
Comment by @aprilnovak:

Something else to think about is that the heat-fluids driver should be able to return densities. Nek can do this, but the `SurrogateHeatDriver` doesn't have this capability. This could be fixed by either:

1. Always using a T/H solver that computes both temperatures and densities, or
2. Reading the initial densities from OpenMC input files and using those to set a `densities_` member in `SurrogateHeatDriver` in the `OpenmcHeatDriver::OpenmcHeatDriver` that is then never updated because the fluid temperature is never updated.

I'll plan on adding something along the lines of option 2 for the time being to streamline the use of a common heat-fluids base class.

**Comment by paulromano** [comment]
Comment by @RonRahaman:

Suppose that, for both `OpenmcNekDriver` and `OpenmcHeatDriver`, `densities_` is initialized from OpenMC.  Then, in a density update from Nek, only the fluid densities are updated; and in a density update from the surrogate, nothing happens.  

This would implement your suggestion from earlier:

> Maybe we could read density of materials from the OpenMC input files, and just never change the solid ones?

which I think is much better than having a dummy value for solid densities.

**Comment by paulromano** [comment]
In the case that we make `densities_` sized according to the number of fluid elements, how would the update happen in `OpenmcNekDriver::update_density`? Right now the structure is something like:
```
for c in OpenMC_cells:
    for element in c:
        T = temperature_[element]
        ...
```
If `densities_` is indexed differently, using `element` as an index won't work.

**Comment by paulromano** [comment]
Comment by @aprilnovak:

Ok so it sounds like having `densities_` be the same length as `temperatures_` would make things easier from an indexing point of view (as well as conceptually). 

I think it would be a nice feature to be able to initialize density using either the OpenMC input file data or from a Nek restart file (similar to temperature). The T/H solver would then never touch the solid densities, and we could skip over those elements using a mask so that we don't bother "udpating" them in the OpenMC inputs.

**Comment by RonRahaman** [comment]
I've started an implementation where `NekDriver` has:
* A `density()` function that returns an xtensor of global element densities.  Its length is `nelgt_`.  For fluid elements, the density is calculated from corrected temperature and pressure.  For non-fluid elements, the density is set to 0.  Its length is `nelgt_`.
* A `fluid_mask()` function that returns an xtensor of ints.  Each value is 0 or 1 depending on if the element is in fluid.  Its length is `nelgt_`.  

My question right now is:  Does it make sense to have `fluid_mask()` declared in the `HeatFluidsDriver` base class?

**Comment by aprilnovak** [comment]
Yes, I think it makes sense to put `fluid_mask()` in the `HeatFluidsDriver` class, since as @paulromano mentioned, the Monte Carlo solver doesn't have a notion of phase. 

After thinking about it a bit more, why set the solid density to zero? Nek knows some information regarding the solid density since it's needed in the solid energy time derivative term. Or is the density unity because Nek solves in nondimensional form?

**Comment by aprilnovak** [comment]
And as for the `SurrogateHeatDriver`, the `fluid_mask()` will be all zeros since there's no T/H solution performed for the fluid region. Just as a note for myself for later, if we want to evaluate convergence later based on density, the change in density norm would always be zero. We'll need some input checking eventually to make sure that the convergence norms make sense for the different solvers.

**Comment by RonRahaman** [comment]
In Nek's setup, the solid's density, $\rho\c_p$, isn't a physical parameter.  

In the [energy equation](http://nek5000.github.io/NekDoc/theory.html#equation-energy) for a steady-state problem in the solid, both the advection and transient terms would be zero, so the density would be cancelled out .  However, we're trying to use a transient solver for a steady-state problem.  Hence the transient term is necessarily non-zero, and the $\rho\c_p$ in the rea file is a solver parameter that doesn't mean density.  Don't know exactly what that means to the solver, but I do know that it doesn't mean solid density.

**Comment by RonRahaman** [comment]
One more thought about the fluid mask...  Would you rather it be a mask (like we've discussed) or an index array (which contains indices to the elements that in fluid)?  For example:

* `{0, 0, 1, 0, 1, 1, 0, 1}` vs.
* `{2, 4, 5, 7}`

One disadvantage of the latter is that it's more work to infer which elements are in *solid*.  If you care about that, I'd be happy to keep it as a mask.

**Comment by aprilnovak** [comment]
Ah, okay. Then an earlier comment of mine that said we could set the density IC either from OpenMC inputs or Nek inputs doesn't make sense - we can only set it from the OpenMC values.

I think a mask is fine, but the other approach is okay as well. If there's an advantage to the second option, we could do that way.
