### ISSUE TITLE
Express power in smrt coupled drivers in neutronics basis

### ISSUE THREAD

**Issue by aprilnovak** [enrico-dev/enrico#42]
If the neutronics and T/H solvers are to be easily swappable, the solution fields known to the coupled drivers have to be represented on the same meshes used in the single-physics drivers that they come from. For example, in `OpenmcNekDriver`, the power is an array of length equal to the number of OpenMC cells. This allows the `OpenmcDriver` to compute this array without any information regarding what T/H solver is used; then, the coupled drivers maps this data computed on the neutronics mesh onto the T/H mesh, which is T/H solver-dependent.

The `ShiftNekDriver` currently stores `d_powers` on the T/H mesh, which means that `ShiftDriver` cannot provide this power, _and_ normalize it, without knowing information from Nek. We should instead change `d_powers` to be of length equal to the number of Shift tally cells, and project that onto the Nek mesh within `ShiftNekDriver` to isolate the single-physics drivers from each other.

**Comment by paulromano** [comment]
SMRT source was recently removed, so this issue is no longer relevant
