### ISSUE TITLE
Consolidate the various T/H surrogates

### ISSUE THREAD

**Issue by aprilnovak** [enrico-dev/enrico#44]
The intention of the surrogate drivers is to permit easier/faster debugging and to provide some acceleration capabilities in the future. It is _not_ the intention of this project to explore the fidelity of one conduction surrogate to another, so we can reduce some physics duplication by combining the `SurrogateHeatDriver`, `Multi_Pin_Conduction`, and `Multi_Pin_Subchannel` classes together into a single T/H surrogate used by both Shift and OpenMC.

The `SurrogateHeatDriver` includes more physics considerations than `Multi_Pin_Conduction`, such as a pellet-clad gap heat transfer coefficient. On the other hand, `SurrogateHeatDriver` has no solution in the fluid phase at all. 

This MR will therefore use the solid solution from `SurrogatHeatDriver` and add the subchannel capabilities from `Multi_Pin_Subchannel` to give a single T/H surrogate. This will involve several steps:

- [x] Add fluid phase solution to `SurrogateHeatDriver`

- [x] Update `OpenmcHeatDriver` to include updates to fluid temperature and density

- [x] Update `Multiphysics_Driver` to use consolidated T/H surrogate with new definitions for data mappings

**Comment by aprilnovak** [comment]
Is there a reason why the solid temperature solution is in `vendor/surrogates` instead of just within the class structure of `SurrogateHeatDriver`? For consistency, I think we should either:

1) move the functionality currently in `vendor/surrogates/heat_xfer_backend.cpp` into `src/surrogate_heat_driver.cpp` to be consistent with the two-group diffusion surrogate, or

2) move the functionality currently in `src/smrt/Two_Group_Diffusion.cpp` into a new file in `vendor/surrogates` to be consistent with the fuel temperature solution.

I prefer approach 1 because we can eliminate a lot of argument passing to function calls we currently have in `heat_xfer_backend.cpp` that could just be member variables instead available from the XML file. Thoughts?

@RonRahaman @paulromano @sphamil

**Comment by aprilnovak** [comment]
I also propose changing the `pin_locations` field to something like `n_pins` and `pitch`, since the subchannel solver won't be able to truly account for arbitrary pin positions without having new functionalities like drawing all the gaps between arbitrarily positioned pins (with some type of nearest-neighbor algorithm) and then using some type of polygon-area calculation to get flow areas and more complicated fractional perimeter calculations for averaging fluid temperatures as solid surface Dirichlet BCs.

Ideas?

**Comment by paulromano** [comment]
The reason the heat conduction surrogate was out in `vendor/` is because it was written by @smharper as part of his (unreleased) Magnolia code. We certainly could move it directly into our source; I wouldn't be opposed to that.

As for the pin locations, the one thing I wonder is what happens if we want to use the surrogate solvers for a multi-assembly problem. Seems like in that case you really would need to know the pin locations for mapping purposes.

**Comment by aprilnovak** [comment]
We can certainly have a `centroid` member on each `Rod` object for mapping between MC cells and the T/H domain - specifying the pin locations using a number of pins and a pitch wouldn't prevent that. 

I think switching to a number of pins and pitch representation reduces tedium in specifying pin coordinates for real-size bundles in real-size cores and makes it clear that the subchannel solver won't work for arbitrary pin locations anyways. For instance, the solver assumes the pins are in a Cartesian grid because it assumes the union of cell-centered squares around each pin is the same as the fluid domain. Even if you specified the pins in a non-Cartesian, but still regular lattice (like hexagonal), the solver still assumes each rod is split between four channels, which would not be the case.

**Comment by aprilnovak** [comment]
I think the project could benefit from moving the Magonlia source into `SurrogateHeatDriver` to allow more flexibility with coupling to the fluid solution (like if we ever wanted to include axial conduction) and to permit greater use of fields already available in `SurrogateHeatDriver` (like node discretizations in the pellet).

@smharper, would that change be okay with you?

**Comment by smharper** [comment]
Yeah, I'm fine with having Magnolia's heat transfer solver moved out of the vendor dir. Same for the IAPWS tables. At some point I've gotta figure out how I want to release the Magnolia solvers, but I probably won't do that soon.

**Comment by paulromano** [comment]
We now have a single surrogate model in ENRICO
