### ISSUE TITLE
GSL Lite submodule?

### ISSUE THREAD

**Issue by RonRahaman** [enrico-dev/enrico#46]
Why isn't GSL Lite a proper submodule?

**Comment by paulromano** [comment]
It certainly could be. I'm used to directly including things for OpenMC since we don't use submodules there, but we are already using submodules for this project and might as well do the same for gsl-lite. Are you offering your services in this regard?

**Comment by RonRahaman** [comment]
I'd like that.  I think using a submodule would really clarify which version of GSL Lite we're using.  Currently in ENRICO, the only version info I can find for GSL Lite `vendor/gsl/CMakeLists.txt`.  If it were a submodule, the version would be much clearer.  We'd also have the `CHANGES.txt` for a quick summary of everything.

**Comment by paulromano** [comment]
Closed with the merging of #47
