### ISSUE TITLE
Namespace nek_interface.h?

### ISSUE THREAD

**Issue by paulromano** [enrico-dev/enrico#6]
Moving issue 3 from gitlab originally submitted by @RonRahaman:

The functions in `nek_interface.h` aren't namespaced (as OpenMC's and STREAM's functions are).  Maybe namespace nek's functions, too?

**Comment by RonRahaman** [comment]
This doesn't make sense, since `nek_interface.h` is a C API.  Perhaps I raised this issue back when we were considering a C++ interface?
