### ISSUE TITLE
Set gsl::index as ptrdiff_t

### ISSUE THREAD

**Issue by RonRahaman** [enrico-dev/enrico#62]
Somewhat orthogonal to #61 

By default, GSL Lite defines `gsl::index` as `size_t`.  This contradicts the contradicts the C++ Core Guidelines, which strongly recommends a signed type for indices.  However, one of the intended features of GSL Lite is the `-Dgsl_CONFIG_SPAN_INDEX_TYPE` macro, which can be used to redefine `gsl::index` ([link](https://github.com/martinmoene/gsl-lite#microsoft-gsl-compatibility-macros)).  

It gets resolved like this in [`gsl-lite.hpp`](https://github.com/martinmoene/gsl-lite/blob/master/include/gsl/gsl-lite.hpp):
```
#ifndef  gsl_CONFIG_SPAN_INDEX_TYPE
# define gsl_CONFIG_SPAN_INDEX_TYPE  size_t
#endif
```
and then:

```
// index type for all container indexes/subscripts/sizes
typedef gsl_CONFIG_SPAN_INDEX_TYPE index;   // p0122r3 uses std::ptrdiff_t
```

Can we set `-Dgsl_CONFIG_SPAN_INDEX_TYPE=ptrdiff_t` when we configure ENRICO?

**Comment by paulromano** [comment]
I was originally going to say that I agree, but looking into it, it's a little complicated apparently. `span` is being standardized and will be part of C++20. They originally had `span::index_type` as being a `ptrdiff_t` and that is what is returned by `span::size()`. However, they've changed course now and `index_type` is actually a `size_t` as of the [latest C++20 draft](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2019/n4820.pdf). So, if we want to be consistent with the C++20 standard, `span::index_type` really should be `size_t`, not `ptrdiff_t`.

You'll notice that to this point I haven't said anything about `gsl::index`. It just so happens that `gsl::index` is typedef-ed to be the span index_type. So, it's kind of a separate question of whether `gsl::index` should be `size_t` or `ptrdiff_t`.

**Comment by RonRahaman** [comment]
Looks like the MS GSL developers have been pretty confused about this too: https://github.com/microsoft/GSL/issues/171

After your comments, I'm more confident with the GS Lite defaults now, so I'm closing this.
