### ISSUE TITLE
Opinion about destructor in Comm

### ISSUE THREAD

**Issue by RonRahaman** [enrico-dev/enrico#80]
I'd like to free a `Comm` in a few places.  I'd like for the `comm` member to be freed, as well as `group`, `size`, and `rank` to be set to null or 0.  

Should I implement this in a destructor?  Or should I have a `free` member function?  

@paulromano

**Comment by paulromano** [comment]
I guess my gut reaction is to have a member function. It's not clear to me that a `Comm` object "owns" the underlying communicator. What would happen if a `Comm` refers to `MPI_COMM_WORLD`?

**Comment by RonRahaman** [comment]
Yeah, that's a good distinction to make.  The `Comm` is like a handle to the underlying communicator.  After I've freed that communicator, I'd still want to retain the handle.

**Comment by RonRahaman** [comment]
Or, in your example, I might want to get rid of the handle without freeing the underlying communicator.

**Comment by RonRahaman** [comment]
A free() member function would also work well with the existing semantics.  If you called free() from an instance, then calling active() later would return false.
