### ISSUE TITLE
Allow builds without Nek5000

### ISSUE THREAD

**Issue by paulromano** [enrico-dev/enrico#92]
In principle, now that we have a consolidated driver, one can use enrico to run a coupled OpenMC+surrogate calculation that doesn't require Nek. It might be nice to allow builds of enrico without Nek. I'm thinking that if `USR_LOC` is not specified or turns up nothing, the build would proceed without Nek enabled and the relevant sections of the code ifdef-ed out.

**Comment by RonRahaman** [comment]
Yeah, I'd support that!

**Comment by paulromano** [comment]
Closed with #98
