### ISSUE TITLE
Error in openmc_driver.cpp

### ISSUE THREAD

**Issue by AI-Pranto** [enrico-dev/enrico#94]
During compiling, I get an error message 
 In Constructor It shows error  ` ‘enrico::OpenmcDriver::OpenmcDriver(MPI_Comm)’:`
`error: ‘FILL_MATERIAL’ is not a member of ‘openmc'` Line>40
and In Member function It shows error
 ` ‘virtual xt::xtensor<double, 1> enrico::OpenmcDriver::heat_source(double) const’:`
`error: ‘RESULT_SUM’ is not a member of ‘openmc’` Line > 90
What is the solution for this error?

**Comment by paulromano** [comment]
It looks like the version of OpenMC that is being built against is not correct -- try running `git submodule update` and rebuilding.

**Comment by AI-Pranto** [comment]
After update git submodule, there's some inconsistency defining source file in CMakeLists.txt to the existing source file in /openmc/src. Like `src/bremsstrahlung.cpp` `src/cmfd_solver.cpp` file is not present in src directory.

**Comment by paulromano** [comment]
Can you paste the exact error you are seeing here?

**Comment by AI-Pranto** [comment]
`CMake Error at vendor/openmc/CMakeLists.txt:309 (add_library):
  Cannot find source file:

    src/bremsstrahlung.cpp

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .m .M .mm .h .hh .h++ .hm
  .hpp .hxx .in .txx


CMake Error at vendor/openmc/CMakeLists.txt:199 (add_library):
  Cannot find source file:

    vendor/faddeeva/Faddeeva.cc

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .m .M .mm .h .hh .h++ .hm
  .hpp .hxx .in .txx


CMake Error at vendor/openmc/CMakeLists.txt:199 (add_library):
  No SOURCES given to target: faddeeva
`

**Comment by paulromano** [comment]
Not sure what exactly is going on. Perhaps try `git submodule update --init --recursive`. If that doesn't work, I would suggest doing a fresh `clone`: `git clone --recurse-submodules https://github.com/enrico-dev/enrico.git`

**Comment by AI-Pranto** [comment]
Thanks @paulromano for your help.

**Comment by AI-Pranto** [comment]
### hypre submodule

`git clone --recurse-submodules https://github.com/enrico-dev/enrico.git` fails to fetch the `hypre` sub-submodule.

```
Cloning into '/home/pranto/Github/AI-Pranto/enrico/vendor/nek5000/3rd_party/hypre/hypre'...
Username for 'https://github.com': AI-Pranto
Password for 'https://AI-Pranto@github.com': 
remote: Repository not found.
fatal: repository 'https://github.com/LLNL/hypre.git/' not found
fatal: clone of 'https://github.com/LLNL/hypre.git' into submodule path '/home/pranto/Github/AI-Pranto/enrico/vendor/nek5000/3rd_party/hypre/hypre' failed
Failed to clone '3rd_party/hypre/hypre'. Retry scheduled
```

**Comment by RonRahaman** [comment]
Uh oh, looks like https://github.com/LLNL/hypre isn't accessible right now.  Nek5000 itself also gets HYPRE from that repo ([link](https://github.com/Nek5000/Nek5000/blob/master/3rd_party/hypre/install)), so it might pose a problem for Nek, too.  Thanks for letting us know!

**Comment by paulromano** [comment]
Interesting, that URL for hypre does give a 404. It looks like the appropriate one is https://github.com/hypre-space/hypre. We pick up this dependency transitively through Nek5000, so it would need to be fixed upstream. @RonRahaman?

**Comment by paulromano** [comment]
Hah, guess we were typing replies at the same time

**Comment by RonRahaman** [comment]
So that dependency is handled slightly differently in our fork of Nek5000 (https://github.com/enrico-dev/Nek5000) and the main repo (https://github.com/Nek5000/Nek5000).  
* In our fork of Nek5000 , it's handled via a submodule that points to github.com/LLNL/hypre
* In the main Nek5000, it's downloaded via a shell script.  That points to the same place as our submodule, so the main repo would also encounter problems.  I raised the issue in https://github.com/Nek5000/Nek5000/issues/668

So both of us have a similar problem, and we'll both need to discover a new source for HYPRE.  The fix will just be implemented slightly differently.

**Comment by RonRahaman** [comment]
I just noticed that NekRS gets HYPRE from a different repo, https://github.com/hypre-space/hypre 

https://github.com/Nek5000/nekRS/blob/ea67c182889899fde55b306f4704b1c1c8741cf4/3rd_party/3rd_party.version#L23

I think I can change the submodule to that.

**Comment by RonRahaman** [comment]
Looks like hypre-space/hypre has the same history as LLNL/hypre.  I don't know if the latter was actually a fork of the former (or vice versa).  But the important part is that the commit that our submodule points to also exists in hypre-space/hypre.  So we should be okay.

**Comment by paulromano** [comment]
@AI-Pranto The issue you were seeing should be resolved now. Let us know if you still have any problems.

**Comment by AI-Pranto** [comment]
Sorry for the late response. @paulromano I fixed the problem by changing the URL for `hypre` submodule manually. Thanks for the fix @RonRahaman
